
import imgBlog1 from './Images/blogImage1.webp'
import imgBlog2 from './Images/blogImage2.webp'
import imgBlog3 from './Images/blogImage3.webp'
import imgBlog4 from './Images/blogImage4.webp'
import imgBlog5 from './Images/blogImage5.webp'
import imgBlog6 from './Images/blogImage6.webp'
import imgBlog7 from './Images/blogImage7.webp'
import imgCont1 from './Images/blog-content-img1.jpg'
import imgCont2 from './Images/blog_cont_img2.webp'
import imgCont3 from './Images/blog_cont_img3.webp'
import imgCont4 from './Images/blog-content-img4.jpg'
import imgCont5 from './Images/blog-content-img5.jpg'
import imgCont6 from './Images/blog_cont_img6.webp'
import imgCont7 from './Images/blog_cont_img7.webp'
import imgCont8 from './Images/blog_cont_img8.webp'
import imgCont9 from './Images/blog_cont_img9.webp'



const dataBlog = [

    {
        id: '1',
        searchTerm: 'blog',
        name: 'Kumbhaka',
        name2: 'Type of Yoga',
        imgBlog: imgBlog1,
        text: "On the effect and purpose of hypoventilation techniques of pranayama. Kumbhaka (breath-holding) as the ultimate form of controlled hypoventilation. Practical recommendations for practitioners of yoga and pranayama.",
        text2: [
            {p: <h2>Kumbhaka: concept</h2>},
            {p: <p>"Kumbhaka" is simultaneously a practice and the outcome of the practice, specifically serving as an indicator of a yogi's level of training in the stage of mastering pranayama according to the eightfold system of yoga by Patanjali. In the "Yoga Sutras," pranayama is described as the "arrest of inhalation and exhalation" [2:49].</p>},
            {p: <p>In general, the word “stop” better reflects the essence of the yogic practice of kumbhaka than the more common translation of the Sanskrit term “breath retention.” Stopping breathing happens spontaneously, naturally and easily, while holding it seems to require efforts aimed at suppressing the body’s natural need to breathe. However, in order for something to happen easily and spontaneously, you need to go for a long time and methodically, developing certain skills and increasing control, which certainly requires effort, diligence and discipline.</p>},
            {p: ``},
            {p: <p>Breath-holding for training purposes can be performed after inhalation, when the air is held inside (antar kumbhaka), or after exhalation, when the air is held outside (bahir kumbhaka).</p>},
            {p: <p>At the initial stage it is recommended to practice antar kumbhaka, because many people find it even psychologically easier (and the brain does not immediately sound the alarm), which allows them to adapt to hypoxic loads. If you perform hyperventilation technique (for example, kapalabhati breathing or bhastrika-pranayama) before stopping breathing, then even a beginner will be able to go beyond the mark of 45 seconds during compensatory delay. And this is the mark that must be overcome to arrive at hypercapnia (see above).
                However, antar kumbhaka (i.e., holding the breath after inhalation) is not as simple a technique as it may seem at first glance. It is important to learn how to hold the air through the coordinated work of the respiratory muscles rather than by constricting the vocal chord.</p>},
            {p: <p>Mechanical blockage of the larynx (when you literally block the air by squeezing the vocal chord) increases intracranial pressure and disrupts metabolic processes in brain tissue. If the vocal cleft is open, the intracranial pressure remains normal. Therefore, the delay should be performed due to static contraction of respiratory muscles stabilizing the position of the chest, against the background of relaxation of other muscle groups. It is no coincidence that the practice of pranayamas is preceded by the practice of yoga asanas: the ability to isolate the work of key muscles and read their proprioceptive response is developed through asana practice.</p>},
            {p: <p><b>As far as bahir kumbhaka is concerned, the following guidelines are worth considering:</b></p>},
            {p: <p><b>1.</b> prolonged exhalation hold should be practiced only with the support of traya bandha, maha mudra, or three locks, as it is necessary to create negative pressure in the chest to ensure adequate blood flow to the brain;</p>},
            {p: <p><b>2.</b> bahir kumbhaka should be practiced only after mastering and long training of antar kumbhaka, because during external delay a person experiences more serious hypoxic load (after full exhalation there is practically no oxygen left in the lungs), and therefore needs additional training of the respiratory system.</p>},
            {p: <br/>},
            {p: <h2>Contraindications</h2>},
            {p: <p>The practice of delays is contraindicated in functional disorders of the cardiovascular and respiratory system, ischemic conditions, various disorders of blood coagulation (both with a tendency to thrombosis and increased bleeding), as well as during pregnancy.</p>},
            {p: <br/>},
            {p: <h2>Kumbhaka: where to start?</h2>},
            {p: <p>Even if you are just starting to practice yoga, and focused work with the breath causes boredom and misunderstanding, combine the practice of yoga asanas with ujjayi breathing, decanting air through the constricted vocal cleft with a characteristic noise and friction. Ujjayi breathing has a weakly pronounced hypoventilation effect, as it allows you to significantly lengthen the respiratory cycle. Therefore, more or less long practice of asanas accompanied by ujjayi will favorably affect the state of mitochondria, and you will get used to keep focus of attention on breathing and learn to control it.</p>},
            {p: <p>When you have learned to relax in shavasana and have developed sufficient motor control to remain still for long periods of time without pronounced discomfort, gradually introduce the practice of prana-vyayamas into your regimen. Prana-vyayamas are a corpus of exercises that allow you to develop and strengthen your respiratory muscles to prepare for the more serious hypoxic stresses of kumbhaka practice. And let it be just one practice per week of 15-20 minutes, the important thing is to repeat it systematically for 2-3 months.</p>},
            {p: <p>A systematic approach to organizing the training process has an accumulative effect. Therefore, after some time you will literally feel a surge of strength and vigor and notice that you are less fixated on destructive thoughts, it is easier to keep your composure in critical situations, it is easier to recover and adapt to new conditions.</p>},
        ]
    },

    {
        id: '2',
        searchTerm: 'blog',
        name: 'Meditation: where to start',
        name2: 'Type of Yoga',
        imgBlog: imgBlog2,
        text: "Practical recommendations for beginners. Typical mistakes and misconceptions at the initial stage.",
        text2: [
            {p: <p>How do I learn to meditate? The very statement of the question implies that we are waiting for instructions on how to attune our mind and body to meditation. But the secret is that the mind and body do not need to be trained in any special way. Meditation should be practiced.</p>},
            {p: <p>Meditation is not some secret technique. It is essentially a practice of self-observation. You become aware of the activity of the mind and the reactions of the psyche in the moment, without engaging in a train of thought or allowing emotions to pull you out of a state of inner balance, open presence and clear awareness.</p>},
            {p: <p>To reach this state, to learn to stay in it for longer than a moment, and if necessary, to return to it at any moment, you can and should practice relaxation and concentration. However, it is important to realize that meditation is not about relaxing to pleasant music or focusing on your own thoughts. Meditation is a transcendent state of mind that "quiets down" as soon as it becomes aware of itself. In this state, consciousness seems to be zeroed out, as filters that "color" the processes of perception and thinking of a person in the color of his beliefs disappear, and at the same time it expands, as all kinds of barriers that limit cognition of oneself and the world are removed.</p>},
            {p: <p>The state of meditation is outside the realm that can be characterized by the apparatus of thinking, that is, described in words, represented in the form of a scheme, graph, formula, etc. Therefore, meditation cannot be taught. The only thing that can be taught is various techniques of relaxation and concentration, which serve as a means of achieving the state of meditation. It is impossible to predict which technique will suit you. Everything depends on the peculiarities of your psyche, the nature of which can only be understood by you, practicing meditation.</p>},
            {p: <p>All sorts of "meditation techniques", which today are presented under the sauce of different schools and methods, in fact, are a set of specific techniques for "curbing the mind" through relaxation and concentration. The actual practice of meditation is reduced to the three actions described above, rather than to the mastery of disparate techniques, but you have to start somewhere (see the article "Meditation Techniques").</p>},
            {p: <img className='img_blog_content_floatLeft' src={imgCont1} alt="blog"/>},
            {p: <p>Of course, at the initial stage it can be very difficult to practice meditation without using these techniques: how to relax if there is something in the body that hurts, itches, pulls or aching, and something in the mind that worries, disturbs and burdens; how to concentrate if thoughts are racing, emotions are taking over, and attention is slipping away. Therefore, below I will give a number of practical recommendations, observance of which will help you to curb your mind and tune in to the practice of meditation, even without knowledge of special techniques, which you can master in the future, if you want to practice meditation in this or that tradition.</p>},
            {p: <p><b>1. Time.</b> It is best to practice meditation at a certain time, then your body will automatically adjust to relaxation and your mind to calmness. In the same way, your digestive organs prepare themselves for food if you stick to a regimen in your diet. Without a doubt, the best time to meditate is early morning when the body is still in a relaxed state and the mind is not cluttered with daily chores and worries. The rarefied state of atmosphere that is celebrated at dawn makes one's mind clearer and more perceptive. This is why morning meditation practice is usually the easiest and most productive (for the benefits of morning practice, see the article "The Best Time for Yoga").</p>},
            {p: <p><b>2. Duration.</b> Start with 5 minutes of meditation a day and gradually increase the duration of practice by 1-2 minutes each week). It is better to move in small steps, but to practice meditation every day, than to set yourself the task of immediately "sitting" 20-30 minutes, then reduce the practice to 15 minutes, and then abandon it altogether.</p>},
            {p: <p><b>3. Frequency.</b> The more frequent, the better. Optimally, every day. Consider that if you skipped meditation today, you took a step backward. And you are unlikely to see the fruits of your practice anytime soon. Prolonged interruptions in practice can lead to emotional instability and even feelings of emptiness. Regular meditation practice, on the other hand, can be your rock in times of instability and crisis.</p>},
            {p: <p><b>4. Location. </b>If possible, choose a place protected from drafts and other external influences: noise, cold, vibrations, etc. If possible, try to do the practice in the same place and/or on the same mat/cushion if you are traveling. As it is always easier to relax and calm down in familiar surroundings. However, even if you didn't bring your yoga mat or favorite meditation cushion with you on your trip, that's no reason to skip the practice.</p>},
            {p: <p><b>5. Clothing.</b> Any comfortable clothing that does not restrict movement, including chest movement. If insects are flying and crawling around, exercise under a net. In a relaxed state the body quickly cools down, so it is not superfluous to put on a shawl or a light plaid for a comfortable stay in a motionless state, if you practice longer than 5-10 minutes.</p>},
            {p: <p><b>6. Position.</b> The optimal position is sitting cross-legged on the floor. If you are unable to bring your knees to pelvic level, place a pillow, bolster or folded blanket under your buttocks. When you sit cross-legged on a support, it is much easier to control the position of your spine and your legs will not get stiff. You can also practice meditation sitting on a chair or sitting on your knees in hero pose. The main condition is that your back should be straight and your position stable, then the load will be evenly distributed between the sciatic bones and along the spinal column. The spinal traction position will allow you to remain awake throughout the practice.</p>},
            {p: <p><b>7. Expectations and outcome.</b> Do not set any expectations. Don't be disappointed or happy about the results of the practice. Even if you are not able to "curb" the mind, you cannot relax and concentrate, your intention to give time to practice, i.e. to try to let go of mental and bodily tension and at least for a few seconds to keep your attention on this or that object, the training effect will be achieved. And next time it will be easier for you! Everyone who practices meditation has encountered frustration and a feeling of wasted time. Don't give up. No skill comes by itself. Every skill has to be developed.</p>},
            {p: <p><b>8. The Power of Intention.</b> Do not try to quiet your mind, i.e., literally silence it, in order to arrive at a state of meditation. Obsession with the result creates excessive mental tension, which, as we already know, must be released: a vicious circle. To attune yourself to meditation, all it takes is your intention to practice: to be aware of the activity of your mind and watch thoughts unfold and reactions arise. It's as if you're on the side of the highway watching the cars whiz by. Or standing beside a stream in an autumn forest and watching dry leaves float by.</p>},
            {p: <p><b>9. Stress.</b> Many people claim that meditation is a stress reliever. The paradox is that one can only come to inner balance and experience the state of meditation (i.e., a state of zeroing in and expanding consciousness) in the absence of stress. Of course, practicing meditation (i.e., trying to reach this state) has a beneficial effect on the psyche and raises the threshold of stress tolerance. People who regularly practice meditation are less susceptible to stressors because they can more easily and quickly switch from being fixated on an idea or emotion.</p>},
            {p: <p><b>10. Relaxation.</b> An important condition for practicing meditation is activation of the parasympathetic mode of functioning of the nervous system, when the body rests and the mind relaxes. Modern man is more often in the state of "run, fight, defend", i.e. in the mode of dominance of the sympathetic part of the autonomic nervous system, when the mind is most excited. To stimulate the parasympathetic nerve fibers, you can perform appropriate breathing techniques with bandhas holding, if you practice pranayama. It will be enough to try to make inhalations deeper and exhalations longer. Deep bends in standing or sitting positions and asanas such as halasana (plow pose), salamba sarvangasana (shoulder stand) are also suitable for activating the parasympathetics. Regular practice of shavasana and/or yoga nidra also helps develop the skill of PSNS activation and conscious relaxation.</p>},
            {p: <p><b>11. Concentration.</b> As an object of concentration for meditation practice, you can choose something that appeals to you on an intuitive level. It can be a sound or a set of sounds (for example, a mantra), an object (both real and imaginary), a symbol (a word or a sign), an image (of a person or a god), a process (breathing, heartbeat, movement of a flame, flow of water), a part of a body (a point in the area between the eyebrows, the tip of a nose), an image (a point on a wall, a photograph of a person, a landscape in a painting), etc. At the initial stage you can try to focus on different objects and points, but with time try to choose one thing for yourself and use only this technique for some time to feel the fruits of your practice. For more information about different concentration techniques, see the article "Meditation Techniques".</p>},
            {p: <p>I hope that these guidelines will allow you to set aside your doubts and put aside your search for miracle recipes and know-how that will teach you how to "meditate". The process of self-discovery begins with your intention to explore the activity of your mind. Practicing meditation will allow you to channel this process and lead you to great discoveries about your potential: you definitely can, and you will succeed. If you learn to control your inner state, you can control the course of your life.</p>},
        ]
        

    },

    {
        id: '3',
        searchTerm: 'blog',
        name: 'Shavasana is a pose for deep relaxation',
        name2: 'Type of Yoga',
        imgBlog: imgBlog3,
        text: "Why it is important to practice shavasana, how to learn to relax, audio accompaniment for shavasana.",
        text2: [
            {p: <p>"Shavasana translates from Sanskrit as "corpse pose" (शव sava [shava] - corpse). It is usually performed after the main practice, but can also be done separately when there is a need for deep relaxation.</p>},
            {p: <p>Sometimes we come across the opinion that shavasana is an unnecessary stage, because there are plenty of more "useful" things to do during this time. If you've been to group classes at the studio, you may have noticed that some practitioners simply leave while the group is settling into shavasana. As a result, a few minutes saved in this way affect the result of the whole practice in a bad way.</p>},
            {p: <p>Look at shavasana not as a waste of time, but as a necessary part of the class. Just as important as the setup and the main asana sequence. Even if you're not tired. Even if you can come and lie down at home in a more comfortable environment. The main task of shavasana is to balance the state of the body and nervous system, to integrate the motor experience gained during the class. Literally "record" it in the motor cortex of the brain and at the level of the fascial system.</p>},
            {p: <p>If you decide to skip shavasana or do it at home, the new pattern of coordination and movement will have a harder time taking hold. You will go home using habitual movement patterns and possibly with an agitated nervous system. It will be much more difficult to come to a dominant harmonious state and to develop new physical competencies with this approach.</p>},
            {p: <br/>},
            {p: <h2>Shavasana Pose</h2>},
            {p: <img className='img_blog_content_floatRight' src={imgCont2} alt="blog"/>},
            {p: <p>Assume a comfortable position lying on your back. Spread your arms and legs slightly to release the groin and axillary lymph nodes. The palms of your hands should be turned upwards. If you feel tension in the back of your neck or throat, you can place a small support under your head, such as a yoga blanket (not a soft one! your head should not fall into it like a featherbed).</p>},
            {p: <p>If there is tension in the lower back or hyperlordosis, you can place a bolster under the knees to help the lower back relax. Then relax the body as much as possible by scanning the body with attention from the bottom up or top down, consciously relaxing the segment where the attention is now.</p>},
            {p: <p>Music for shavasana is not obligatory, but you can play a track that is pleasant to the ear. It is desirable that the composition should be without words or at least in an unfamiliar language: such accompaniment will attract less attention, because it will be needed to track bodily sensations.</p>},
            {p: <br/>},
            {p: <h2>Preparing for Savasana</h2>},
            {p: <p><b>1.</b> Keep warm even if you don't feel cold yet. When your body is lying still, you may feel a slight chill after 3 to 5 minutes. This will prevent your muscles from fully relaxing and your mind from calming down. Put on a sweater and warm socks beforehand or cover yourself with a blanket.</p>},
            {p: <p><b>2.</b> Stop the hustle and bustle of the mind. If shavasana is voice-guided, focus on the sensations in the areas of the body that the teacher's voice is guiding you through. By immersing yourself in them, you will literally switch your perception from mental "bubblegum" to bodily sensations, which will enhance the effect of shavasana.</p>},
            {p: <p>If you are doing shavasana without voice accompaniment and cannot distract yourself from intrusive thoughts, switch to observing the breath. Repeat to yourself on each inhale/exhale cycle, observing the depth and rhythm of your breathing. If you notice you get distracted, just go back again and repeat the "inhale-outhale" to yourself. The brain can't match such counting and the work of the brain's anxiety center, the amygdala, which generates and races around anxious thoughts. After a few minutes they will go away, only breathing and deep relaxation will remain.</p>},
            {p: <p><b>3.</b> Use a shavasana pad, it works on two levels at once:</p>},
            {p: <p><b>- Superficial.</b> It blocks the access of light through the eyelids, it generally helps to relax.</p>},
            {p: <p><b>- At the level of the nervous system.</b> The gentle pressure prevents the eyeballs from moving and the oculomotor muscles are allowed to relax. This, in turn, reduces the tension level of the mind and nervous system as a whole.</p>},
            {p: <img className='img_blog_content_floatRight' src={imgCont3} alt="blog"/>},
            {p: <p>Additionally, pressure on the eyeballs activates the ocular-cardiac reflex known as the Diving Reflex or Aschner-Dagnini reflex.</p>},
            {p: <p>This is a kind of "switch" for the nervous system, transitioning from sympathetic activity mode (increased heart rate, mobilization of resources for movement and activity) to a predominance of the parasympathetic mode (maintaining homeostasis, rest, tissue repair, and restoration of energy resources).</p>},
            {p: <p>If you can't relax in shavasana, it's likely that your natural sympathetic/parasympathetic switching mechanism is disrupted due to chronic stress. It is all the more important to learn to relax after activity. If this skill is not restored, it is a direct path to burnout, sleep disorders and nervous exhaustion.</p>},
            {p: <p>Training the ability to relax needs to be approached like any other skill: by practicing yoga and shavasana regularly, with full immersion and focus.</p>},
            {p: <p>Wishing you health and a comfortable shavasana!</p>},
        ]
    },

    {
        id: '4',
        searchTerm: 'blog',
        name: 'Yoga practice and the phases of the female cycle',
        name2: 'Healthy Yoga',
        imgBlog: imgBlog4,
        text: "How to align your yoga practice with a woman's cycle.",
        text2: [
            {p: <p>The path of yoga is open to everyone, regardless of age, gender or health status. Both men and women can practice yoga. But since they have different physiology, the practice of asanas and pranayamas for women has its own peculiarities that should be taken into account.</p>},
            {p: <p>The daughter of the famous yoga master B.K.S. Iyengar, Gita Iyengar, was the first to publicize this. In her book "Yoga Practice for Women Throughout the Cycle" she justified the necessity to adapt the practice based on the peculiarities of functioning of female hormonal and reproductive systems.</p>},
            {p: <p><i>"When it comes to the principles of yoga, sincerity in approach and application of methodology are not different. However, when it comes to the practice of asana and pranayama, their application in sadhana (practice) is different. Women should pay attention to this in order to maintain their physical and mental health."</i></p>},
            {p: <p>There is another, rather categorical point of view: yoga practice is universal and should not be adapted for women. What position to follow, whether to practice yoga during periods is a woman's personal choice. We will give recommendations on the organization of practice taking into account the phases of the cycle for those who are ready to observe and focus on their own well-being.</p>},
            {p: <br/>},
            {p: <h2>Peculiarities of yoga practice in different phases of the cycle</h2>},
            {p: <p>The first day of the cycle is the day when menstruation begins. The average cycle length is 28 days. If your cycle is longer or shorter, the length of the phases may change. You can notice their change by observing your health and the general tone of your body.</p>},
            {p: <p><b>Practice in the follicular phase (estrogenic), following the completion of menstruation.</b></p>},
            {p: <p>High estrogen levels stimulate fibroblasts, the cells that make collagen. This is important for renewing and strengthening the ligaments of the uterus, which is preparing for possible fertilization. At the same time, collagen is actively synthesized in all connective tissues: cartilage, bones, tendons, etc., and their density also increases.</p>},
            {p: <img className='img_blog_content_floatRight' src={imgCont4} alt="blog"/>},
            {p: <p>This process is helped by increased production of somatotropin, a growth hormone. Its level is high in this phase, which means that protein is actively synthesized and decomposed more slowly, fat is deposited more slowly, and the ratio of fat to muscle changes in favor of muscle tissue.</p>},
            {p: <p>It can be said that this phase is the monthly peak of physical fitness. Practicing during this period is almost the same as for men. Strength training, statics and interval training are good.</p>},
            {p: <p>It is useful to perform inverted asanas, abdominal manipulations, especially favorable is uddiyana bandha, as it mechanically lifts the internal organs. (Attention! There are contraindications!)</p>},
            {p: <p>This is important, because in the previous phase under the influence of cortisol and progesterone stretch the walls of veins, ligaments, internal organs slightly lowered.</p>},
            {p: <p>It is recommended to work with the pelvic floor muscles, practice breathing techniques with forced inhalation.</p>},
            {p: <p><b>Practice during the ovulatory phase</b></p>},
            {p:<p>If this phase of the cycle proceeds normally and you feel good, then the practice can be continued as usual. With an emphasis on performing inverted asanas in various variations.</p>},
            {p: <p>If there are problems with the cycle or conception, it is recommended during this period to exclude such complex deflections as urdhva dhanurasana (full bridge), kapotasana (pigeon pose), vrishchikasana (scorpio pose). And concentrate on performing forward extensions and inverted asanas.</p>},
            {p: <p>If you still want to perform asanas for spinal extension, you should do this with props: provide support for the pelvic area or place your legs on an elevation so that the pelvis is higher than the level of the chest. And pay special attention to the correct execution technique, that is, pull the lower third of the abdomen inward and upward, draw in the lower ribs.</p>},
            {p:<p><b>Practice in the luteal phase (progesterone phase)</b></p>},
            {p:<p>Under the influence of progesterone, degradation of connective tissue gradually begins. It is considered a cortisol synergist; together they suppress the functioning of fibroblasts, slowing down the renewal and compaction of connective tissue.</p>},
            {p:<p>Smooth muscles weaken, which means that it is better to exclude techniques such as agnisara dhauti kriya. Especially if there is a predisposition to prolapse, dysplasia, etc. It is also not recommended to hold long static positions - holding asanas for more than 30 seconds.</p>},
            {p: <p>During this phase of the cycle, it is good to practice asanas for stretching all lines of the body, dynamic practices in the vinyasa flow style, you can practice inverted positions, abdominal manipulations (agnisara dhauti with caution or exclude).</p>},
            {p:<p><b>Practicing yoga during menstruation</b></p>},
            {p:<p>The task of this stage is the evacuation of the old endometrium.</p>},
            {p:<p>To help the process, sequences of asanas consisting of simple stretches are recommended.</p>},
            {p:<img className='img_blog_content_floatLeft' src={imgCont5} alt="blog"/>},
            {p: <p>For example, adho mukha virasana, janu shirshasana, etc., poses for opening the hip joints in a sitting or lying position (for example, upavista konasana, badhakonasana, malasana, etc.). They will relieve tension in the abdomen and lower back, relax the cervix, which will facilitate the evacuation of blood and endometrium.</p>},
            {p: <p>The best breathing practices are Nadi Shodhana Pranayama or its preparatory version, Anuloma Viloma.</p>},
            {p:<p>At this time, it is worth spending more time on relaxation techniques: performing a long shavasana or yoga nidra practice.</p>},
            {p:<p><b>What to exclude:</b></p>},
            {p:<p><b>1. All inverted asanas, i.e.</b> such poses in which the pelvis is higher than the heart. Inverted positions interfere with the natural flow of menstrual blood and the release of the endometrium. This disrupts the natural cleansing processes and can lead to hormonal imbalance, and in the worst case, stopping your period.</p>},
            {p:<p>Also, in inverted positions, due to a decrease in intra-abdominal pressure, conditions are created for the retrograde flow of blood and endometrium. Its cells can begin to develop in the fallopian tubes, ovaries, intestinal tissues, bladder, etc. and degenerate under the influence of hormonal fluctuations during subsequent cycles.</p>},
            {p:<p><b>2. Asanas with pressure and compression of the abdominal cavity</b> (for example, navasana, mayurasana, dhanurasana), also deep twists (marichyasana, ardha matsyendrasana, etc.). They create tension in the abdominal area and can increase bleeding and cause cramping.</p>},
            {p:<p><b>3. Forced breathing practices, bandhas</b> (for example, uddiyana bandha, mula bandha, kapalbhati, bhastrika, agnisara dhauti, nauli). They lower intra-abdominal pressure, change the direction of movement of menstrual blood, and make evacuation more difficult. If there is heavy discharge and poor health in the first 1-2 days, the practice should be postponed. If the menstrual cycle is painless, then the practice is simply adjusted taking into account the above contraindications during this period.</p>},
            {p:<p>It is especially important to follow these recommendations if your periods are painful. This indicates dysfunction and there is a possibility that proper practice will help reduce soreness. If this is your case, try a simple set of two exercises:</p>},
            {p:<p><b>1. baddhakonasana</b> (5 minutes of holding, without tension);</p>},
            {p:<p><b>2. Marjariasana cycle</b>, sometimes called “cat-cow” in dynamics (3-5 minutes).</p>},
        ]
    },

    {
        id: '5',
        searchTerm: 'blog',
        name: 'Carnation: purpose and effect of practice',
        name2: 'Healthy Yoga',
        imgBlog: imgBlog5,
        text: "What the practice of standing on nails gives, how a sadhu board should be used, and where to start.",
        text2: [
            {p: <p>Standing on nails is still perceived as an exotic ability of yogis, which demonstrates great willpower and the ability to abstract from pain. However, it is nothing more than a preventive procedure available to every person who is conscious about taking care of his or her health.</p>},
            {p: <p>Today, so-called sadhu boards (in Sanskrit, "sadhaka" or "sadhu" means disciple and "sadhana" means practice) are produced especially for this procedure. Standing on a sadhu board is an ascesis, a training of the will, an influence on energy flows, and a practice of mindfulness that helps to renew mental and motor patterns.</p>},
            {p: <p>In this article, we will take a closer look at all aspects of this practice.</p>},
            {p: <br/>},
            {p: <h2>Physiology</h2>},
            {p: <p>The most obvious benefit of standing on nails is the stimulation of physiological processes that have health-promoting effects on the body.</p>},
            {p: <p>The average urban person's feet are shod in uncomfortable shoes and walk on hard, flat surfaces such as tiles, asphalt, or the floor of the house. The complex mechanics of the foot remains unused, as there is not enough movement in the small joints, which means that the trophic (i.e. nutrition) of tissues is disturbed. As a result, fatty, muscular, connective tissues, which should provide movement and cushioning of the feet, begin to accumulate residual products of cellular metabolism, and lymph, due to the prolonged lack of muscle activity, is simply unable to remove the accumulated products of cell metabolism and remove them from the body through the excretory system.</p>},
            {p: <br/>},
            {p:<img className='img_blog_content_floatLeft' src={imgCont6} alt="blog"/>},
            {p: <br/>},
            {p: <p>The practice of standing on nails powerfully stimulates blood and lymph flow in these stale tissues. In response to a pain signal, the immune system sends its "agents" - immune cells - out to explore. As a result of their activity, waste products of metabolism are eliminated, cell nutrition is improved, and the conscious triggering of such a process develops proprioception (body awareness).</p>},
            {p: <p>Important! Standing on nails does not eliminate the need to work the feet and perform special exercises. The more attention you pay to them, the better. Do not transfer to nails the work that should be realized through proper motor activity</p>},
            {p: <p>Below we provide links to popular video lessons at Yanta Yoga School that will thoroughly work your feet and improve ankle mobility.</p>},
            {p: <br/>},
            {p: <h2>Consciousness and subconsciousness</h2>},
            {p: <p>In addition to influencing the interconnected energetic and physiological aspects of the body's functioning, standing on nails has a powerful effect on the state of consciousness.</p>},
            {p: <p>Standing on nails is an uncompromising “here-and-now.” If you find it difficult to distract yourself from the endless stream of thoughts and truly experience the present moment, practice is a great way to do this. When nails dig into the soles of your feet, it’s hard to let your thoughts wander to an unfinished conversation or half-cooked soup. As a result, this practice also affects perception: it becomes sharper and clearer.</p>},
            {p: <p>The pain suffered, strong unlived emotions “settle” in our body for years, and sometimes for the rest of our lives. The body reacts to them with muscle tension, trying to either protect vulnerable parts or pull away, “run away” from the source of pain. We may not even notice it, but over time this tension will reshape the entire pattern of movement and manifest as pathology, and not necessarily at the point of tension itself, but in any place where it is transmitted through the fascial network.</p>},
            {p: <p>When we stand on nails, we also encounter pain. This is a conscious action, we need to prepare for it, but when we find ourselves on nails, we find ourselves face to face with our defensive strategies and automatisms. And in this moment there is a powerful potential for transformation if you manage to direct your attention correctly.</p>},
            {p: <p>How does your body react? What is your mind screaming about? What emotions arise and what do you do with them? It is quite possible that you (unconsciously) constantly reproduce all these reactions in life. They are built into you, grown over the years, they determine your choice at the moment and, ultimately, its result. If you want to get some other results, identify these strategies, notice them in your daily life and try to replace them with others that will lead to the desired results. How long you will have to stand on nails for this depends on your mental fitness, but changes can begin after the first session.</p>},
            {p: <br/>},
            {p:<img className='img_blog_content_floatLeft' src={imgCont7} alt="blog"/>},
            {p: <p><b>What is the difference between nails and the Lyapko/Kuznetsov/pranamat applicator?</b></p>},
            {p: <p>The applicator needles are designed for contact with the skin of any part of the body; they are more rounded. This reduces the likelihood of injury, but also reduces the acupuncture effect. Nails reach deeper layers of tissue and act much more intensely. Of course, standing on a prickly mat is better than not stimulating your feet at all, but you shouldn’t count on a deep effect.</p>},
            {p: <br/>},
            {p: <h2>Standing on nails technique</h2>},
            {p: <p>It is recommended to do a short yoga asana practice or meditation beforehand: this will help to set the mood and calm the mind. Standing on the nails in an agitated state or in strong emotions, especially negative ones, will make it difficult to bear the pressure, and instead of calmness and ease, you may get an escalation of negative feelings.</p>},
            {p: <p><b>Important:</b> Make sure that there are no skin lesions or fungal diseases on the feet. Even if the board is personal, you should not practice nailing if the skin is damaged.</p>},
            {p: <p>For beginners and people with hypersensitivity, it is advisable to start by standing on the board from a chair and with support (e.g. on a table or on an assistant's arm). This allows the body weight to be distributed on 2 feet at once and reduces discomfort. In time you will be able to step onto the board from a standing position, but it is still desirable to have a support at hand: a table, your mentor's hands, a chair, a handrail, etc. It is optimal to practice every day. If you don't have such an opportunity - no worries, choose a convenient mode for you. As in any training, regularity and systematicity are important.</p>},
            {p: <p>The sensation of standing on nails is, to put it bluntly, unusual and the body may be perceived as a danger. This means that it is automatically mobilized: the musculature tones up, the head "goes" into the shoulders, the eye-motor and suboccipital muscles tense up, and breathing becomes shallow. If you keep this tension in the body, the practice of nailing will not have any beneficial effect.</p>},
            {p: <p>After surviving the first seconds of shock, you need to gradually release the tension in the muscles and let them "flow" to the feet. If you practice yoga, the skill of relaxing muscles that are not involved in movement has already been practiced. If not, it will take more time to do it, but sooner or later the skill will be formed.</p>},
            {p: <p>How long to stand depends on your training. You can start with 10 seconds, gradually increasing the time little by little. Advanced practitioners stand on the nails for about half an hour on average. When you manage to stand quietly for several minutes, from time to time you can do "stepping over": slightly change the position of your feet on the board to involve more energy points.</p>},
            {p: <p>Standing on nails can only be harmful if you are overly sensitive: if your nervous system and psyche are very reactive, the sensations will be too vivid and will bring nothing but stress. In such a case, you can start practicing sitting until the sensations become habitual, or you can give it up. The practice will be ineffective if you remain in tension all the time without trying to get rid of it and accept pain, discomfort and resistance of the mind as part of the practice.</p>},
        ]
    },

    {
        id: '6',
        searchTerm: 'blog',
        name: 'Yoga nidra - effectiveness',
        name2: 'Type of Yoga',
        imgBlog: imgBlog6,
        text: "What is yoga nidra and how to practice it properly.",
        text2: [
            {p: <p>Modern scientists, as well as ancient yoga masters, agree that a person operates only a small part of the brain's resources. Most of them remain inaccessible, hidden deep in the subconscious. In a normal state of consciousness a person has no access to them, as he cannot interact with his subconscious mind directly.</p>},
            {p: <p>Yoga nidra gives you the opportunity to open access to the subconscious mind in a state of deep relaxation. If you perform this technique regularly, you can solve everyday tasks more creatively, assimilate new knowledge more effectively, and most importantly, get rid of the burden of accumulated tension and prevent various psychosomatic disorders.</p>},
            {p: <p>During the day, the mind's resources are spent processing information that comes through the sensory perception organs and related cognitive processes. At the edge of sleep and wakefulness, the brain is in a state of inhibition: the wave activity of the cerebral cortex is significantly reduced, while its receptivity remains very high. The brain stops reacting to external stimuli, but does not fall into sleep, in this state there is spontaneous contact with the sphere of the unconscious: a person is gently immersed in the bowels of his psyche. As Swami Satyananda, the founder of the method, writes: "If consciousness is separated from both external perception and sleep, it is filled with power that can be used for various purposes: strengthening memory, accumulating knowledge, increasing creativity, transforming the whole personality.</p>},
            {p: <p>It is important to realize that yoga nidra is not meditation or sleep, it is a very special technique of conscious psychophysical relaxation, which is based on 2 conditions:</p>},
            {p: <p>- awake consciousness;</p>},
            {p: <p>- full involvement of the mind in the process of gradual relaxation.</p>},
            {p: <p>If these conditions are met, correctly voiced information is assimilated many times faster than in the normal state of consciousness.</p>},
            {p: <p>The experiment often cited as evidence involves Swami Satyananda, who was tasked with educating a difficult child in an ashram. The student was a real troublemaker, and traditional educational methods were not effective with him. That's when Satyananda decided to try teaching through yoga nidra. He would read excerpts from the sacred scripture Bhagavad Gita to the boy as soon as he began to doze off. Within a week of such sessions, the unruly student had completely absorbed the text. In the end, he learned more than 10 languages in two years and mastered many complex texts without spending hours poring over books.</p>},
            {p: <h2>Technique</h2>},
            {p: <br/>},
            {p:<img className='img_blog_content_floatLeft' src={imgCont8} alt="blog"/>},
            {p: <p>The optimal position for a yoga nidra session is shavasana, a pose of complete relaxation. As an exception, it is permissible to take a position lying on your side, sitting and even standing, but this will not have the best effect on the effect of the practice.</p>},
            {p: <p>The leader reads the text of the nidra, drawing the listener’s attention to all parts of the body in a certain sequence. Following such instructions does not require analysis or any intellectual effort at all; as a result, inhibition processes begin to predominate in the cerebral cortex, and a state close to a trance occurs. From analyzing everyday stimuli, attention switches to contemplation.</p>},
            {p: <p>In addition to moving attention around the body, the practitioner is asked to reproduce certain visual images in the mind. The ability for such reproduction is different for all people, it depends on the imagery of thinking, so ideally the text should be compiled individually, for a specific practitioner.</p>},
            {p: <p>In modern conditions, when nidra is usually practiced in groups, it is often impossible to take into account the peculiarities of everyone’s perception or to prepare a separate yoga nidra practice for beginners, so the leader selects a relatively universal text that contains both visual images and instructions for managing attention in an average proportion. Thus, online yoga nidra is no less effective than in a group.</p>},
        ]
    },

    {
        id: '7',
        searchTerm: 'blog',
        name: 'Mantra OM',
        name2: 'Type of Yoga',
        imgBlog: imgBlog7,
        text: "The purpose and effect of mantras in yoga practice, the impact and technique of performing the mantra OM / AUM.",
        text2: [
            {p: <p>The mantra OM or AUM is the most famous mantra and is often chanted in yoga classes. What sacred meaning does the OM mantra have and what effect does this sound vibration create?</p>},
            {p: <h2>How do mantras work?</h2>},
            {p: <br/>},
            {p: <p>Translated from Sanskrit, “man” means “mind” and “tra” means freedom. Thus, mantra is the liberation of the mind through sound. However, the effect of the mantra is not limited to the mental level.</p>},
            {p: <p><b>At the level of consciousness</b></p>},
            {p: <p>It is believed that mantras store potential energy, which manifests itself through sound. By working with a mantra, we release this energy and tune into the vibrations that set the tone for our own “sound” and influence our state of consciousness.</p>},
            {p: <p>After you chant the OM mantra just three times, you will notice how your mind calms down and your attention switches from external stimuli to internal processes.</p>},
            {p: <p>Therefore, it is useful to begin and end a yoga practice with a mantra. The mantra as a key allows you to initiate the process of transition to a transcendental state at the beginning of practice, and at the end - to capture the achieved result and switch to worldly affairs in an altered state of consciousness.</p>},
            {p: <p><b>At the level of the physical body and psychosomatics</b></p>},
            {p: <p>Measured singing in a comfortable position with a straight back trains the respiratory system, and with regular repetition it helps to increase the excursion of the diaphragm. It is important to concentrate on extracting sound from the lower abdomen and smoothly leading it from bottom to top along the spinal column.</p>},
            {p: <p>Mantropenia can also work on the principle of sound therapy: measured singing of vowels helps relieve tension in the throat and relax the vocal cords. With regular chanting of mantras, your voice can change: it becomes smoother, deeper, richer in modulation.</p>},
            {p: <p>If you are very familiar with the feeling of a lump in the throat, have difficulty expressing emotions or needs, you often suffer from sore throats, laryngitis, etc., chanting mantras will have a good preventive effect: the less tension in the throat, the better the blood and lymph flow, and This means that the immune system will be much more effective in dealing with pathogens on the mucous membranes of the throat.</p>},
            {p: <p><b>At the nervous system level</b></p>},
            {p: <p>The functioning of the nervous system, in addition to hormones and neurotransmitters, is regulated by neuropeptides. This is the least studied group of compounds, which plays an important role in the regulation of eating and sexual behavior, controls circadian rhythms, affects the immune system and is involved in maintaining homeostasis (internal balance).</p>},
            {p: <p>Neuropeptides, among other things, are involved in the creation of new neural connections. From a yogic perspective, increased neuropeptide activity is experienced as “mind clearing” or “enlightenment.” New neural connections form new neural networks that directly affect a person’s cognitive abilities, change his picture of the world and reveal his creative potential. It is as if a person reads more information from everyday situations and objects and thereby deepens the perception of reality.</p>},
            {p: <p>Scientists have found that repeating mantras increases neuropeptide activity and promotes the creation of new neural connections. Therefore, the idea that mantras can “open up new worlds” is not without a neurophysiological basis.</p>},
            {p: <p><b>At the level of the subtle body</b></p>},
            {p: <p>When you throw a stone into the calm surface of a lake, it creates circles. Similarly, with constant repetition of a mantra, the power of sound expands in the lake of the mind and penetrates into every cell of the body, thereby purifying the physical, mental and pranic body. Thanks to this ability of mantras to influence our condition, mantrotherapy is widely used in Ayurveda, the ancient Indian science of a healthy lifestyle. It is believed that mantras can influence the flow of prana in the body, stimulate marmas (important energy points) and have a beneficial effect on the chakras. This effect of mantras not only balances the psychoenergetic state, but also creates a protective shell on the pranic, and therefore on the mental level.</p>},
            {p: <p>Each mantra can be practiced separately and recited repeatedly for a long time, then it will be the practice of mantra yoga.</p>},
            {p: <p>To fully experience the effect of mantras, it is good to have at least a rough idea of ​​the meaning of the words and sounds that you pronounce, and, of course, understand the purpose and pronunciations. But even without knowledge of Sanskrit, you seem to be imbued with the meaning of each word, completely merging with it.</p>},
            {p: <p>If you still find it difficult to choose and don’t know which mantra is right for you, start your practice with the universal mantra OM and see for yourself its effectiveness.</p>},
            {p: <img className='img_blog_content_floatLeft' src={imgCont9} alt="blog"/>},
            {p: <h2>Mantra OM / AUM: meaning</h2>},
            {p: <br/>},
            {p: <p>The Sanskrit word OM or more accurately AUM is considered sacred in many religions and traditions. Thus, in Hinduism it is generally accepted that it was with this vibration that the universe began. In Buddhism, this sacred fusion of sounds is believed to be the key to the liberation of consciousness.</p>},
            {p: <p>The Sanskrit symbol AUM is made up of three elements: two letters and an image of a crescent moon with a dot on top ॐ. This symbol can often be found both in temples and in places where yoga is practiced, without connection with any religion.</p>},
            {p: <h2>How to chant the OM/AUM mantra correctly</h2>},
            {p: <br/>},
            {p: <p>In ancient descriptions and manuals for the practice of yoga, many metaphors and figurative descriptions are given that clarify how the AUM mantra should sound: “the sound should flow slowly and continuously like a stream of oil”, “ring like the resonating hum of a bell”, “the sound should be soft and even like the buzzing of a bee."</p>},
            {p: <p>Here are more specific recommendations on the technique of performing the AUM mantra:</p>},
            {p: <p><b>1.</b> Start pronouncing the sound “A” from the lower abdomen. The sound of AUM originates at the base of the spine and rises to the very top of the head - this is how you need to visualize the movement of the sound at the moment of its pronunciation.</p>},
            {p: <p><b>2.</b> The sound A barely noticeably flows into the sound U somewhere in the region of the heart, but do not try to specifically pronounce U - the change in overtone occurs naturally.</p>},
            {p: <p><b>3.</b> When the sound reaches the larynx, close your lips and it will sound like M. Consciously direct the sound higher, through the area between the eyebrows and release it through the crown.</p>},
            {p: <p><b>4.</b> The mantra should sound smooth, soft, continuous and very natural. At first, the voice may tremble, the tone may change, and breathing may be interrupted. However, over time and with regular practice, everything will level out and you (and people around you) will notice that your voice has become calmer and the timbre of your voice is more pleasant.</p>},
            {p: <p>Common mistakes:</p>},
            {p: <p>- mechanical execution of a mantra (a person is busy with his thoughts and does not work with sound from within)</p>},
            {p: <p>- contraction of the abdominal muscles in the last seconds (when the air is running out, just finish, no need to squeeze out the sound and strain the abdominal muscles)</p>},
            {p: <p>- facial muscle tension (make sure you are not wincing or tense your facial muscles)</p>},
            {p: <p>- incorrect tonality (too high a tone) and excessive intensity (the sound of AUM is pronounced in a low tone, without unnecessary tension)</p>},
            {p: <p>Take these recommendations into account, but try not to get hung up on the technical side of extracting the AUM sound. Just surrender to the flow and be filled with this sound. To produce AUM vibration is a natural ability and need of our body.</p>},
            {p: <p>Before chanting AUM, you can do any pranayama or shatkarma. So, for example, after a session of kapalbhati or pranayama nadi shodhana, AUM sounds much richer and longer. It is noted that after practicing yoga asanas and, especially, after relaxing in shavasana, the AUM mantra sounds much smoother and richer than before the start of practice.</p>},
            {p: <p>If after 8-10 times of reciting the AUM mantra you experience deep peace and peace of mind, then you are doing everything right! Don't be discouraged if it doesn't work right away, and don't be ashamed of your unsightly singing and false notes. Over time, you will definitely feel a qualitative improvement in your performing abilities, but most importantly - your well-being and general condition.</p>},
            {p: <p>On our website there is a separate practice of mantropenia, during which you repeat the mantra OM 108 times after performing a set of pranayamas. There are also separate video lessons that begin and end with the mantra OM. There are also entire practices in the style of vinyasa flow, which are accompanied from start to finish by ancient mantras in a modern sound.</p>},
            {p: <p>Enrich your practice with mantras. This is an excellent tool that allows you to harmonize the state of mind and body, calm the nervous system, promote the creation of new neural connections and maintain neuroplasticity of the brain.</p>},
        ]
    }
]

export default dataBlog;